package com.hanielfialho.api.registry;

import com.hanielfialho.api.command.CommandMetadata;
import com.hanielfialho.api.source.CommandSource;
import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import com.mojang.brigadier.tree.LiteralCommandNode;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

/**
 * Adapter used to plug CommandEngine into a platform Brigadier dispatcher.
 */
public interface BrigadierAdapter {

    @NotNull
    CommandDispatcher<CommandSource> getDispatcher();

    /**
     * Registers a Brigadier root generated by the processor.
     */
    default @NotNull LiteralCommandNode<CommandSource> register(
            @NotNull LiteralArgumentBuilder<CommandSource> root, @NotNull CommandMetadata metadata) {
        return register(Objects.requireNonNull(root, "root").build(), metadata);
    }

    /**
     * Registers a Brigadier root node already built by the processor.
     */
    default @NotNull LiteralCommandNode<CommandSource> register(
            @NotNull LiteralCommandNode<CommandSource> root, @NotNull CommandMetadata metadata) {
        Objects.requireNonNull(metadata, "metadata");
        getDispatcher().getRoot().addChild(Objects.requireNonNull(root, "root"));
        return root;
    }

    /**
     * Removes a previously registered root when the platform supports it.
     * Adapters that do not support dynamic unregistration may leave this as a no-op.
     */
    default void unregister(@NotNull String name) {
        Objects.requireNonNull(name, "name");
    }
}
