/*
 * Copyright (c) 2026 Haniel Fialho
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.hanielfialho.api.registry;

import com.hanielfialho.api.command.CommandMetadata;
import com.hanielfialho.api.source.CommandSource;
import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import com.mojang.brigadier.tree.LiteralCommandNode;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

/**
 * Adapter used to plug CommandEngine into a platform Brigadier dispatcher.
 */
public interface BrigadierAdapter {

    @NotNull
    CommandDispatcher<CommandSource> getDispatcher();

    /**
     * Registers a Brigadier root generated by the processor.
     */
    default @NotNull LiteralCommandNode<CommandSource> register(
            @NotNull LiteralArgumentBuilder<CommandSource> root, @NotNull CommandMetadata metadata) {
        return register(Objects.requireNonNull(root, "root").build(), metadata);
    }

    /**
     * Registers a Brigadier root node already built by the processor.
     */
    default @NotNull LiteralCommandNode<CommandSource> register(
            @NotNull LiteralCommandNode<CommandSource> root, @NotNull CommandMetadata metadata) {
        Objects.requireNonNull(metadata, "metadata");
        getDispatcher().getRoot().addChild(Objects.requireNonNull(root, "root"));
        return root;
    }

    /**
     * Removes a previously registered root when the platform supports it.
     * Adapters that do not support dynamic unregistration must override this method.
     */
    default void unregister(@NotNull String name) {
        Objects.requireNonNull(name, "name");
        throw new UnsupportedOperationException("Dynamic unregistration is not supported by this adapter");
    }
}
